USE [master]
GO

/****** Object:  Login [sa1]    Script Date: 28.10.2020 9:11:56 ******/
DROP LOGIN [sa1]
GO

CREATE LOGIN [sa1] WITH PASSWORD=N'1q2w3e4r5t!', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER LOGIN [sa1] DISABLE
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [sa1]
GO

ALTER LOGIN [sa1] ENABLED
GO




USE [master]
GO

/****** Object:  Database [PI_Temp]    Script Date: 28.10.2020 8:53:56 ******/
DROP DATABASE [PI_Temp]
GO

/****** Object:  Database [PI_Temp]    Script Date: 28.10.2020 8:53:56 ******/
CREATE DATABASE [PI_Temp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PI_Temp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PI_Temp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PI_Temp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PI_Temp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PI_Temp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PI_Temp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PI_Temp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PI_Temp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PI_Temp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PI_Temp] SET ARITHABORT OFF 
GO

ALTER DATABASE [PI_Temp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PI_Temp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PI_Temp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PI_Temp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PI_Temp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PI_Temp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PI_Temp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PI_Temp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PI_Temp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PI_Temp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PI_Temp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PI_Temp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PI_Temp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PI_Temp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PI_Temp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PI_Temp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PI_Temp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PI_Temp] SET RECOVERY FULL 
GO

ALTER DATABASE [PI_Temp] SET  MULTI_USER 
GO

ALTER DATABASE [PI_Temp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PI_Temp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PI_Temp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PI_Temp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PI_Temp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PI_Temp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PI_Temp] SET  READ_WRITE 
GO


