'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Indusoft.I_OMS_Client.Calculators.API.LD15TToVM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Температура повітря.
        '''</summary>
        Friend ReadOnly Property AmbTemperature() As String
            Get
                Return ResourceManager.GetString("AmbTemperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LD15TToVM.
        '''</summary>
        Friend ReadOnly Property const_UID() As String
            Get
                Return ResourceManager.GetString("const_UID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Густина робоча.
        '''</summary>
        Friend ReadOnly Property Density() As String
            Get
                Return ResourceManager.GetString("Density", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Густина15.
        '''</summary>
        Friend ReadOnly Property Density15() As String
            Get
                Return ResourceManager.GetString("Density15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Густина20.
        '''</summary>
        Friend ReadOnly Property Density20() As String
            Get
                Return ResourceManager.GetString("Density20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Рівень.
        '''</summary>
        Friend ReadOnly Property Level() As String
            Get
                Return ResourceManager.GetString("Level", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LevelD.
        '''</summary>
        Friend ReadOnly Property LevelD() As String
            Get
                Return ResourceManager.GetString("LevelD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Мертвий залишок.
        '''</summary>
        Friend ReadOnly Property MassDead() As String
            Get
                Return ResourceManager.GetString("MassDead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на MassMax.
        '''</summary>
        Friend ReadOnly Property MassMax() As String
            Get
                Return ResourceManager.GetString("MassMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Маса.
        '''</summary>
        Friend ReadOnly Property MassTotal() As String
            Get
                Return ResourceManager.GetString("MassTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Маса продукту корисна.
        '''</summary>
        Friend ReadOnly Property MassWork() As String
            Get
                Return ResourceManager.GetString("MassWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|AmbTemperature.
        '''</summary>
        Friend ReadOnly Property Path_AmbTemp() As String
            Get
                Return ResourceManager.GetString("Path_AmbTemp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|Density.
        '''</summary>
        Friend ReadOnly Property Path_Density() As String
            Get
                Return ResourceManager.GetString("Path_Density", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|Density15.
        '''</summary>
        Friend ReadOnly Property Path_Density15() As String
            Get
                Return ResourceManager.GetString("Path_Density15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|Density20.
        '''</summary>
        Friend ReadOnly Property Path_Density20() As String
            Get
                Return ResourceManager.GetString("Path_Density20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|Level.
        '''</summary>
        Friend ReadOnly Property Path_Level() As String
            Get
                Return ResourceManager.GetString("Path_Level", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|MassDead.
        '''</summary>
        Friend ReadOnly Property Path_MassDead() As String
            Get
                Return ResourceManager.GetString("Path_MassDead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|MassMax.
        '''</summary>
        Friend ReadOnly Property Path_MassMax() As String
            Get
                Return ResourceManager.GetString("Path_MassMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|MassTotal.
        '''</summary>
        Friend ReadOnly Property Path_MassTotal() As String
            Get
                Return ResourceManager.GetString("Path_MassTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|MassWork.
        '''</summary>
        Friend ReadOnly Property Path_MassWork() As String
            Get
                Return ResourceManager.GetString("Path_MassWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|TankState.
        '''</summary>
        Friend ReadOnly Property Path_TankState() As String
            Get
                Return ResourceManager.GetString("Path_TankState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|Temperature.
        '''</summary>
        Friend ReadOnly Property Path_Temp() As String
            Get
                Return ResourceManager.GetString("Path_Temp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|VolumeTotal.
        '''</summary>
        Friend ReadOnly Property Path_VolumeTotal() As String
            Get
                Return ResourceManager.GetString("Path_VolumeTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Common|ObjectAliasNames|VolumeWork.
        '''</summary>
        Friend ReadOnly Property Path_VolumeWork() As String
            Get
                Return ResourceManager.GetString("Path_VolumeWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Стан резервуару.
        '''</summary>
        Friend ReadOnly Property TankState() As String
            Get
                Return ResourceManager.GetString("TankState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Температура.
        '''</summary>
        Friend ReadOnly Property Temperature() As String
            Get
                Return ResourceManager.GetString("Temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на DeadVolume.
        '''</summary>
        Friend ReadOnly Property VolumeDead() As String
            Get
                Return ResourceManager.GetString("VolumeDead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на MaxVolume.
        '''</summary>
        Friend ReadOnly Property VolumeMax() As String
            Get
                Return ResourceManager.GetString("VolumeMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Обєм продукту.
        '''</summary>
        Friend ReadOnly Property VolumeTotal() As String
            Get
                Return ResourceManager.GetString("VolumeTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на VolumeWork.
        '''</summary>
        Friend ReadOnly Property VolumeWork() As String
            Get
                Return ResourceManager.GetString("VolumeWork", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
